# This workflow posts the wheels build summary as a PR comment.
# It uses `workflow_run` to securely post comments on PRs from forks,
# where the default GITHUB_TOKEN is read-only.
#
# How it works:
# 1. Your main CI workflow builds wheels and uploads them as artifacts
# 2. This workflow triggers after the CI workflow completes
# 3. It downloads the artifacts and generates + posts the summary comment
# 4. Because `workflow_run` runs in the base repo context, it has write
#    permissions even for fork PRs
#
# Setup:
# - Save this as `.github/workflows/post-summary-comment.yml`
# - Replace "CI" in the `workflows` list with your CI workflow's name
# - Replace "wheels-*" with your artifact name pattern
# - Adjust the `require-matrix` to match your build matrix

name: Post Build Summary

on:
  workflow_run:
    # Replace "CI" with the name of your build workflow
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    # Only run on successful completions (or use `always()` equivalent below)
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          # Download artifacts from the triggering workflow run
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          pattern: wheels-*
          path: all-wheels

      - name: Generate build summary
        uses: patrick91/wheels-ci-action@main
        with:
          wheels-path: all-wheels
          post-comment: "false"
          # Adjust require-matrix to match your build configuration
          require-matrix: |
            [
              {
                "platform": "Linux*",
                "versions": "3.8-3.14,3.14t,PyPy3.9-3.11"
              },
              {
                "platform": "Windows x64",
                "versions": "3.8-3.14,3.14t"
              },
              {
                "platform": "macOS*",
                "versions": "3.8-3.14,3.14t,PyPy3.9-3.11"
              }
            ]

      - name: Post PR comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the PR number from the workflow run
          PR_NUMBER=$(gh api \
            repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} \
            --jq '.pull_requests[0].number')

          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
            echo "Could not determine PR number, skipping comment."
            exit 0
          fi

          SUMMARY_FILE="${{ runner.temp }}/wheels-summary.md"
          if [ -f "$SUMMARY_FILE" ]; then
            gh pr comment "$PR_NUMBER" \
              --repo ${{ github.repository }} \
              --body-file "$SUMMARY_FILE" \
              --edit-last 2>/dev/null || \
            gh pr comment "$PR_NUMBER" \
              --repo ${{ github.repository }} \
              --body-file "$SUMMARY_FILE"
          fi
