# This workflow posts the wheels build summary as a PR comment.
# It uses `workflow_run` to securely post comments on PRs from forks,
# where the default GITHUB_TOKEN is read-only.
#
# How it works:
# 1. Your main CI workflow generates the summary and uploads it as an artifact
# 2. This workflow triggers after the CI workflow completes
# 3. It downloads the summary artifact and posts it as a PR comment
# 4. Because `workflow_run` runs in the base repo context, it has write
#    permissions even for fork PRs
#
# Setup:
# 1. Save this as `.github/workflows/post-summary-comment.yml`
# 2. Replace "CI" in the `workflows` list with your CI workflow's name
# 3. In your CI workflow's summary job, add a step to upload the summary:
#
#    - name: Upload build summary
#      if: github.event_name == 'pull_request'
#      uses: actions/upload-artifact@v4
#      with:
#        name: build-summary
#        path: ${{ runner.temp }}/wheels-summary.md

name: Post Build Summary

on:
  workflow_run:
    # Replace "CI" with the name of your build workflow
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    name: Post PR Comment
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Download build summary
        uses: actions/download-artifact@v4
        with:
          name: build-summary
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Get PR number
        id: pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Try the workflow run's pull_requests array first (works for same-repo PRs)
          PR_NUMBER=$(gh api \
            repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} \
            --jq '.pull_requests[0].number // empty')

          # For fork PRs, pull_requests is empty — search by head SHA instead
          if [ -z "$PR_NUMBER" ]; then
            HEAD_SHA=${{ github.event.workflow_run.head_sha }}
            PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open \
              --json number,headRefOid \
              --jq ".[] | select(.headRefOid == \"$HEAD_SHA\") | .number")
          fi

          echo "number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Post PR comment
        if: steps.pr.outputs.number
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: wheels-ci-summary
          number: ${{ steps.pr.outputs.number }}
          path: wheels-summary.md
